### PR TITLE
[PAR-WDFT-248] Laurent Vuillaume

### PR DESCRIPTION
**Pull request by figura01**
Done

### CODE REVIEW

**Comment by N10T** [comment]
Hello can you format the title of your pull request as followed please:
[PAR-WDFT-248] YOUR NAME if you are in the Paris bootcamp.

Without this, we can not know who you are.

**Comment by figura01** [comment]
Done

**Comment by figura01** [comment]
> Hello can you format the title of your pull request as followed please:
> [PAR-WDFT-248] YOUR NAME if you are in the Paris bootcamp.
> 
> Without this, we can not know who you are.

Hi, Andy sorry for my bad manipulation, i corrected now :D

**Comment by N10T** [comment]
Cool I'll check it

**Comment by N10T** [comment]
Hey Laurent,

**The behaviour:**
Your page looks the same 💯  but...
- the original green footer looks taller

**HTML**
- use prettier extension for a better automatic indentation
- have the logo in the green footer as an image add an extra work => use it as background maybe ;)



**CSS**
- prefer to use flexbox than absolute position and transform (text of the landing page)
- for sizing prefer to use px/vw/vh/% than rem or em if it's not a text

👍

**Pull request closed without merging**
